---
title: "EMB markers and annotation"
author: "EP"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE, warning = FALSE, message = FALSE}

options (width = 100)
knitr::opts_chunk$set(warning = FALSE, echo = TRUE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234

```




```{r, echo=FALSE, message=FALSE, warning=FALSE, Load all required packages}

#library(ExploreSCdataSeurat3)
#library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
library(shiny)
library(org.Hs.eg.db)
library(EnhancedVolcano)
library(ImmunoLogic)
library(presto)



```


```{r, echo  = F}
#seuratM <- readRDS("~/Documents/GitHub/Myocarditis EMB Project v3/data/Merged snRNAseq #EMBs/EMB_Myocarditis_onlyAM_23.02.26_filt_SCtransform_doubletremoval_annotated_cleaned")

#seuratM <- readRDS("~/Documents/GitHub/Myocarditis EMB Project v3/data/Merged snRNAseq #EMBs/EMB_Myocarditis_onlyAM_23.02.26_filt_SCtransform_doubletremoval_annotated_cleaned_TCsubgroupsMetadata.rds")

seuratM <- readRDS("~/Documents/GitHub/Myocarditis EMB Project v3/data/Merged snRNAseq EMBs/EMB_Myocarditis_SC_transformed_doublet_removal_annotated_full_metadata_09_3_26")

table(seuratM$orig.ident)
table(seuratM$clusterName)


```



```{r, echo = F}
#seuratM <- readRDS("~/Documents/01 Projects/00 snRNAseq/00 #Myocarditis/data/Merged/Myocarditis_all_files_layers_20.02.26_filt.rds")


#seuratM <- readRDS("~/Documents/01 Projects/00 snRNAseq/00 #Myocarditis/data/Merged/Myocarditis_all_files_layers_20.02.26_filt_annotated.rds")

#seuratM <- readRDS("~/Documents/01 Projects/00 snRNAseq/00 #Myocarditis/data/Merged/Myocarditis_all_files_layers_22.02.26_filt_annotated.rds")

#seuratM <- readRDS("~/Documents/01 Projects/00 snRNAseq/00 #Myocarditis/data/Merged/Myocarditis_all_files_layers_22.02.26_filt_annotated_doubletsremovedv5_normal_scaling_AM_on#ly.rds")

#seuratM <- readRDS("~/Documents/01 Projects/00 snRNAseq/00 #Myocarditis/data/Merged/Myocarditis_all_files_layers_22.02.26_filt_annotated_doubletsremovedv5_SCtransform_scaling_#AM_only.rds")

#seuratM <- readRDS(seuratM, file="~/Documents/01 Projects/00 snRNAseq/00 #Myocarditis/data/Merged/Myocarditis_all_files_layers_23.02.26_filt_annotated_SCtransform_doubletremoval.rds") 
#= saveRDS(seuratM, file="~/Documents/GitHub/Myocarditis EMB Project v3/data/Merged scRNAseq #PBMCs/EMB_Myocarditis_23.02.26_filt_SCtransform_doubletremoval")

#saveRDS(seuratM, file="~/Documents/GitHub/Myocarditis EMB Project v3/data/Merged snRNAseq EMBs/EMB_Myocarditis_onlyAM_23.02.26_filt_SCtransform_doubletremoval_annotated_cleaned_TCsubgroupsMetadata")

## after SC Transform and doublet removal 23.02.2026 --> seuratM <- subset(seuratM, !RNA_snn_res.0.8 %in% c("21", "22", "26","28", "30", "31")) --> 34623 nuclei, #seuratM <- subset(seuratM, !clusterName %in% c("Fb2")), cluster 7

#table(seuratM$orig.ident)


```


```{r}
Idents(seuratM) <- seuratM$RNA_snn_res.0.25

levels(seuratM)
markers <- FindAllMarkers(seuratM, only.pos = T) %>%
                            dplyr::filter(p_val_adj < 0.01)



markers <- markers %>% 
  mutate(Gene=gene) %>%
  mutate(gene=gsub("^.*\\.", "", Gene))  %>%
  mutate(EnsID=gsub("\\..*","", Gene))


Idents(seuratM) <- seuratM$RNA_snn_res.0.25
DimPlot(seuratM, reduction = "umap",label = TRUE, repel = TRUE)
#View(markers)

```
```{r}
#saveRDS(seuratM, file="~/Documents/GitHub/Myocarditis EMB Project v3/data/Merged snRNAseq #EMBs/EMB_Myocarditis_onlyAM_23.02.26_filt_SCtransform_doubletremoval_annotated_cleaned")



```







```{r, echo = F}
Idents(seuratM) <- seuratM$RNA_snn_res.0.25


seuratM$clusterName <- "clusterName"
Idents(seuratM) <- seuratM$clusterName
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "0" )] <- "Fb"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "1" )] <- "Tcells"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "2" )] <- "BEC1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "3" )] <- "PeriFb1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "4" )] <- "CM"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "5" )] <- "InflMph"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "6" )] <- "ResMph"
#seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "7" )] <- "Fb2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "8" )] <- "PeriFb2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "9" )] <- "BEC2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "10" )] <- "NC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "11" )] <- "VSMC"
#seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "12" )] <- "Fb2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "13" )] <- "Bcells"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "14" )] <- "NC"
#seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "15" )] <- "AdipoC"


#colclusterName <- c("#f4a582", "#e34a33", "#FEE08B", "#feb24c","#fff7bc", "#43a2ca", #"#355C7D","#3288BD","#a6bddb", "#a8ddb5", "#01665e", "#66C2A5", "#e5f5e0","#ece2f0","#253494", "#BEAED4", #"#67001f","#fde0dd","#B45B5C","#fa9fb5","#D53E4F")


colclusterName <- c("#fcc5c0" ,"#f4a582", "#FEE08B", "#feb24c","#8c2d04", "#01665e", "#66C2A5", "#807dba", "#355C7D","#3288BD","#a6bddb", "red3", "#91003f")


#016450

names(colclusterName) <-c("CM", "Fb", "PeriFb1", "PeriFb2", "VSMC", "BEC1", "BEC2", "NC",  "ResMph","InflMph", "Bcells", "Tcells")

#colpat_sub<- c("#dfc27d","#BE3144","#355C7D", "#779d8d")

seuratM$clusterName <- factor(seuratM$clusterName, levels=c("CM", "Fb", "PeriFb1", "PeriFb2", "VSMC", "BEC1", "BEC2", "NC",  "ResMph","InflMph", "Bcells", "Tcells"))

Idents(seuratM) <- seuratM$RNA_snn_res.0.25
DimPlot(seuratM, reduction = "umap",label = TRUE, repel = TRUE)

Idents(seuratM) <- seuratM$clusterName
DimPlot(seuratM, reduction = "umap",label = TRUE, repel = TRUE, cols = colclusterName)

Idents(seuratM) <- seuratM$clusterName
DimPlot(seuratM, reduction = "umap",label = F, repel = TRUE, cols = colclusterName)

#table(seuratM$pat_sub)

table(seuratM$orig.ident)

table(seuratM$clusterName)
```

```{r, fig.width = 7, fig.height = 12}

Idents(seuratM) <- seuratM$clusterName
DimPlot(seuratM, reduction = "umap",label = TRUE, repel = TRUE, cols = colclusterName)

genesPlot <- data.frame(gene= c("TTN", "MYBPC3", "RYR2", "TNNT2", "COL6A3", "DCN",  "FBN1", "C7", "PDGFRA", "PDGFRB", "NOTCH3", "MYH11", "ACTA2","PECAM1", "VWF", "EGFL7", "POSTN", "ITGA10", "NRXN1", "ANK3", "PTPRZ1", "CNTN2", "SNAP25", "ICAM1", "CD163", "LYVE1", "MRC1", "SIGLEC1", "STAB1", "CSF1R","MERTK", "SEMA4A", "HLA-DQB1", "CCR2", "IGHM", "GZMB", "IFNG", "IL7R","CD3E", "PTPRC", "CD2", "CD3E"))

#pdf("heatmap marker genes scRNAseq PBMC.pdf", width = 8, height = 14) 
avgHeatmap(seuratM, selGenes = genesPlot, annotation_colors = colclusterName)

#dev.off()

avgHeatmap(seuratM, selGenes = c("TTN", "MYBPC3", "RYR2", "TNNT2", "COL6A3", "DCN",  "FBN1", "C7", "PDGFRA", "PDGFRB", "RGS5", "NOTCH3", "MYH11", "ACTA2","PECAM1", "VWF", "EGFL7", "POSTN", "ITGA10", "NRXN1", "ANK3", "PTPRZ1", "CNTN2", "SNAP25", "ICAM1", "CD163", "LYVE1", "MRC1", "SIGLEC1", "STAB1", "CSF1R","MERTK", "CD79A", "HLA-DQB1", "CCR2", "IGHM", "GZMB", "IFNG", "IL7R","CD3E", "PTPRC", "CD2", "CD3E"), annotation_colors = colclusterName)
#dev.off()

genes <- data.frame(gene=rownames(seuratM)) %>% 
  mutate(geneID=gsub("^.*\\.", "", gene))

genesPlot <- data.frame(geneID=rev(c("TTN", "MYBPC3", "RYR2", "TNNT2", "COL6A3", "DCN",  "FBN1", "C7", "PDGFRA", "PDGFRB", "RGS5", "NOTCH3", "MYH11", "ACTA2","PECAM1", "VWF", "EGFL7", "POSTN", "ITGA10", "NRXN1", "ANK3", "PTPRZ1", "CNTN2", "SNAP25", "ICAM1", "CD163", "LYVE1", "MRC1", "SIGLEC1", "STAB1", "CSF1R","MERTK", "MS4A1", "HLA-DQB1", "CD79A", "HLA-DQB1", "CCR2", "IGHM", "GZMB", "IFNG", "IL7R","CD3E", "PTPRC", "CD2", "CD3E", "CXCL10"))) %>% left_join(., genes, by="geneID") %>% filter(gene != "ENSG00000232995.RGS5") 

#pdf(file="~/Documents/GitHub/Myocarditis EMB Project v3/docs/EMBs/snRNAseq_EMB_allcells_marker_genes_heatmap.pdf")
avgHeatmap(seuratM, selGenes = genesPlot, annotation_colors = colclusterName)
#dev.off()

```

## umap Inflamed vs. non inflamed
```{r}

table(seuratM$Inflammation_status)

Idents(seuratM) <- seuratM$Inflammation_status


colCondition <- c("#fc9", "#BE3144")
names(colCondition) <- c("Non-inflamed", "Inflamed")

seuratInflamed <- subset(seuratM, Inflammation_status == "Inflamed")
#pdf(file="~/Documents/GitHub/Myocarditis EMB Project v3/docs/EMBs/snRNAseq_EMB_Inflamed.pdf", width = 10)
DimPlot(seuratInflamed, reduction = "umap", pt.size = 0.1, cols = colCondition, raster=FALSE)
#dev.off()


seuratNonInflamed <- subset(seuratM, Inflammation_status == "Non-inflamed")
#pdf(file="~/Documents/GitHub/Myocarditis EMB Project v3/docs/EMBs/snRNAseq_EMB_NonInflamed.pdf", width = 10)
DimPlot(seuratNonInflamed, reduction = "umap", pt.size = 0.1, cols = colCondition, raster=FALSE)
#dev.off()

```



```{r}
#seuratM <- subset(seuratM, !clusterName %in% c("Fb2"))

#table(seuratM$orig.ident)


```




```{r, echo = F}

Idents(seuratM) <- seuratM$RNA_snn_res.0.1

DimPlot(seuratM, reduction = "umap", label = TRUE)

Idents(seuratM) <- seuratM$RNA_snn_res.0.15

DimPlot(seuratM, reduction = "umap", label = TRUE)

Idents(seuratM) <- seuratM$RNA_snn_res.0.2

DimPlot(seuratM, reduction = "umap", label = TRUE) 

Idents(seuratM) <- seuratM$RNA_snn_res.0.25

DimPlot(seuratM, reduction = "umap", label = TRUE) #%>% ggplotly

Idents(seuratM) <- seuratM$RNA_snn_res.0.3

DimPlot(seuratM, reduction = "umap", label = TRUE) 

Idents(seuratM) <- seuratM$RNA_snn_res.0.4

DimPlot(seuratM, reduction = "umap", label = TRUE)

Idents(seuratM) <- seuratM$RNA_snn_res.0.6

DimPlot(seuratM, reduction = "umap", label = TRUE)

Idents(seuratM) <- seuratM$RNA_snn_res.0.8

DimPlot(seuratM, reduction = "umap", label = TRUE)



Idents(seuratM) <- seuratM$RNA_snn_res.0.25

DimPlot(seuratM, reduction = "umap", label = TRUE)

table(seuratM$RNA_snn_res.0.8)


```

```{r}
Idents(seuratM) <- seuratM$RNA_snn_res.0.8

levels(seuratM)
markers <- FindAllMarkers(seuratM, only.pos = T) %>%
                            dplyr::filter(p_val_adj < 0.01)



markers <- markers %>% 
  mutate(Gene=gene) %>%
  mutate(gene=gsub("^.*\\.", "", Gene))  %>%
  mutate(EnsID=gsub("\\..*","", Gene))

View(markers)
```



```{r}
Idents(seuratM) <- seuratM$RNA_snn_res.0.8



go_results <- list()

# Loop 
for (i in 0:31) {
  # Subset DE genes for cluster i
  cluster_genes <- markers %>% 
    filter(cluster == as.character(i)) %>% 
    pull(EnsID) %>% 
    unique()


  if (length(cluster_genes) > 0) {
    ego <- enrichGO(gene = cluster_genes,
                    OrgDb = org.Hs.eg.db,
                    keyType = "ENSEMBL",
                    ont = "BP",
                    pAdjustMethod = "BH",
                    pvalueCutoff = 0.05,
                    qvalueCutoff = 0.05)

   
    ego <- setReadable(ego, OrgDb = org.Hs.eg.db)

   
    go_results[[paste0("Cluster_", i)]] <- ego

   
    barplot(ego, showCategory = 5, title = paste("Cluster", i), font.size = 14)
  }
}

for (i in 0:31) {
  cluster_name <- paste0("Cluster_", i)
  ego <- go_results[[cluster_name]]

  if (!is.null(ego) && nrow(ego@result) > 0) {
   
   print(barplot(ego,
            showCategory = 20,
            title = paste("Cluster", i),
            font.size = 8))
  } else {
    message("GO terms for Cluster ", i)
  }
}

```


```{r}
Idents(seuratM) <- seuratM$RNA_snn_res.0.8
DimPlot(seuratM, reduction = "umap",label = TRUE, repel = TRUE)

table(seuratM$RNA_snn_res.0.8)

```


```{r}
seuratM <- subset(seuratM, !RNA_snn_res.0.8 %in% c("21", "22", "26","28", "30", "31"))

table(seuratM$orig.ident)

```

```{r}
seuratM <- subset(seuratM, !RNA_snn_res.0.8 %in% c("20", "7"))

table(seuratM$orig.ident)
```


## FeaturePlots
```{r }

get_full_gene_name <- function(gene, obj){
  return(grep(gene,rownames(obj), value =TRUE))
}
get_full_gene_name("CD3E",seuratM) 


Idents(seuratM) <- seuratM$RNA_snn_res.0.25
DimPlot(seuratM, reduction = "umap", pt.size = 0.3, label = TRUE)

FeaturePlot(seuratM, features = get_full_gene_name("CD3D",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = get_full_gene_name("CD3E",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000010610.CD4", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000090339.ICAM1", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000164692.COL1A2", pt.size = 1, cols = c("lightgrey", "#BE3144")) # Fibroblast

FeaturePlot(seuratM, features = get_full_gene_name("COL4A4",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("FCGR1A",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000107796.ACTA2", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("IFNGR1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = get_full_gene_name("ICAM1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("CSF1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000185591.SP1", pt.size = 1, cols = c("lightgrey", "#BE3144"))


FeaturePlot(seuratM, features = get_full_gene_name("GREM2",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = get_full_gene_name("BMP4",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = get_full_gene_name("SEMA4A",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("CLEC4A",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = get_full_gene_name("CLEC4A",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
```


```{r }

#FeaturePlot(seuratM, features = get_full_gene_name("TNTT2",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("MYH6",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("MYH7",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))



# Visualize the expression of specific marker genes on UMAP
FeaturePlot(seuratM, features = "ENSG00000164692.COL1A2", pt.size = 1, cols = c("lightgrey", "#BE3144")) # Fibroblast
FeaturePlot(seuratM, features = "ENSG00000142173.COL6A2", pt.size = 1, cols = c("lightgrey", "#BE3144")) # Fibroblast
FeaturePlot(seuratM, features = "ENSG00000113721.PDGFRB", pt.size = 1, cols = c("lightgrey", "#BE3144")) # Fibroblast

FeaturePlot(seuratM, features = "ENSG00000135424.ITGA7", pt.size = 1, cols = c("lightgrey", "#BE3144")) # 
FeaturePlot(seuratM, features = "ENSG00000143248.RGS5", pt.size = 1, cols = c("lightgrey", "#BE3144")) # Perivasc Fibroblast

FeaturePlot(seuratM, features = "ENSG00000110799.VWF", pt.size = 1, cols = c("lightgrey", "#BE3144")) # ECs

FeaturePlot(seuratM, features = "ENSG00000179776.CDH5", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000174059.CD34", pt.size = 1, cols = c("lightgrey", "#BE3144")) # endothelial cells

FeaturePlot(seuratM, features = "ENSG00000118194.TNNT2", pt.size = 1, cols = c("lightgrey", "#BE3144")) # cardiomyocyte
#FeaturePlot(seuratM, features = get_full_gene_name("MYH6",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#CM
FeaturePlot(seuratM, features = "ENSG00000078814.MYH7B", pt.size = 1, cols = c("lightgrey", "#BE3144")) # cardiomyocyte

FeaturePlot(seuratM, features = "ENSG00000163110.PDLIM5", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000177575.CD163", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000182578.CSF1R", pt.size = 1, cols = c("lightgrey", "#BE3144"))
#FeaturePlot(seuratM, features = get_full_gene_name("LYVE1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# 

FeaturePlot(seuratM, features = "ENSG00000081237.PTPRC", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000168685.IL7R", pt.size = 1, cols = c("lightgrey", "#BE3144"))
#FeaturePlot(seuratM, features = get_full_gene_name("CD3E",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
```


```{r }
FeaturePlot(seuratM, features = get_full_gene_name("CD3D",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("CD3G",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("CD79B",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("JCHAIN",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("S100A9",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144")) #neutrophil
FeaturePlot(seuratM, features = get_full_gene_name("HLA-DMB",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144")) #MHC expressing macrophages
FeaturePlot(seuratM, features = get_full_gene_name("ACACB",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#adipocytes
FeaturePlot(seuratM, features = get_full_gene_name("PLIN1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#adipocytes
FeaturePlot(seuratM, features = get_full_gene_name("GPAM",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#adipocytes
FeaturePlot(seuratM, features = get_full_gene_name("ITGA7",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("ITGA1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = get_full_gene_name("CD69",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000185811.IKZF1", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000139187.KLRG1", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000110324.IL10RA", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000011465.DCN", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000175084.DES", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000133110.POSTN", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000261371.PECAM1", pt.size = 1, cols = c("lightgrey", "#BE3144"))
#FeaturePlot(seuratM, features = get_full_gene_name("ITGA10",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# BEC
#FeaturePlot(seuratM, features = get_full_gene_name("CDH11",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# BEC

FeaturePlot(seuratM, features = "ENSG00000133392.MYH11", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000107796.ACTA2", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = get_full_gene_name("EGFL7",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# EC BEC und LEC
FeaturePlot(seuratM, features = get_full_gene_name("CDH11",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#endothelial cells
FeaturePlot(seuratM, features = get_full_gene_name("CCL21",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# 
FeaturePlot(seuratM, features = get_full_gene_name("PROX1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# 
FeaturePlot(seuratM, features = get_full_gene_name("FLT4",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# LEC
FeaturePlot(seuratM, features = get_full_gene_name("LYVE1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# 


FeaturePlot(seuratM, features = "ENSG00000149591.TAGLN", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000138755.CXCL9", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000169245.CXCL10", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("CXCL11",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000137573.SULF1", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000125378.BMP4", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = get_full_gene_name("GREM1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#
FeaturePlot(seuratM, features = get_full_gene_name("GREM2",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = get_full_gene_name("THEMIS",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000211592.IGKC", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000078098.FAP", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000179915.NRXN1", pt.size = 1, cols = c("lightgrey", "#BE3144")) # neuron
FeaturePlot(seuratM, features = "ENSG00000198910.L1CAM", pt.size = 1, cols = c("lightgrey", "#BE3144"))
```


```{r }
FeaturePlot(seuratM, features = get_full_gene_name("CD79A",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells
FeaturePlot(seuratM, features = get_full_gene_name("IGHM",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells
FeaturePlot(seuratM, features = get_full_gene_name("CD20",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells
FeaturePlot(seuratM, features = get_full_gene_name("MS4A1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells MS4A1 (CD20)
FeaturePlot(seuratM, features = get_full_gene_name("IGHM",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells
FeaturePlot(seuratM, features = get_full_gene_name("BLNK",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells
FeaturePlot(seuratM, features = get_full_gene_name("IGHM",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells
FeaturePlot(seuratM, features = get_full_gene_name("PRDM1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# Plasma cells PRDM1 (Blimp-1)
FeaturePlot(seuratM, features = get_full_gene_name("IRF4",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#  
```

```{r}
## Baroreceptors: PIEZO1, TRPV2, and TRPM4,

FeaturePlot(seuratM, features = get_full_gene_name("PIEZO1",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells
FeaturePlot(seuratM, features = get_full_gene_name("TRPV2",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# Plasma cells PRDM1 (Blimp-1)
FeaturePlot(seuratM, features = get_full_gene_name("TRPM4",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#  


FeaturePlot(seuratM, features = get_full_gene_name("TURBB3",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# B cells
FeaturePlot(seuratM, features = get_full_gene_name("ASIC2",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# Plasma cells PRDM1 (Blimp-1)
FeaturePlot(seuratM, features = get_full_gene_name("NEFH",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#
FeaturePlot(seuratM, features = get_full_gene_name("ASIC2",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))# Plasma cells PRDM1 (Blimp-1)
FeaturePlot(seuratM, features = get_full_gene_name("NEFH",seuratM) , pt.size = 1, cols = c("lightgrey", "#BE3144"))#

```














