---
title: "snRNAseq EMB all clusters GSEA pathways"
author: "EP"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE, fig.path = "custom/path", warning = FALSE, message = FALSE}

options (width = 100)
knitr::opts_chunk$set(warning = FALSE, echo = TRUE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234

```




```{r, echo=FALSE, message=FALSE, warning=FALSE, Load all required packages}

#library(ExploreSCdataSeurat3)
#library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
library(shiny)
library(org.Hs.eg.db)
library(EnhancedVolcano)
library(ImmunoLogic)
library(presto)



```


```{r, echo  = F}


seuratM <- readRDS("~/Documents/GitHub/Myocarditis EMB Project v3/data/Merged snRNAseq EMBs/EMB_Myocarditis_onlyAM_23.02.26_filt_SCtransform_doubletremoval_annotated_cleaned_TCsubgroupsMetadata.rds")


table(seuratM$orig.ident)
table(seuratM$clusterName)


```


```{r}
Idents(seuratM) <- seuratM$clusterName
DEGenesM<- FindAllMarkers(seuratM, only.pos = F, logfc.threshold = 0.2) %>%
                                      dplyr::filter(p_val_adj < 0.01)

DEGenes <- DEGenesM %>% 
  mutate(Gene=gene) %>%
  mutate(gene=gsub("^.*\\.", "", Gene))  %>%
  mutate(EnsID=gsub("\\..*","", Gene))

View(DEGenes)
```


```{r}
DEGenesFb <- DEGenes %>% filter(cluster == "Fb")

egoFb <- enrichGO(gene = unique(DEGenesFb$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)

egoFb <- setReadable(egoFb, OrgDb = org.Hs.eg.db)


dotplot(egoFb, showCategory=20, title = "Fb", font.size = 10)

View(egoFb@result)

# myeloid leukocyte differentiation, 	 positive regulation of chemotaxis, defense response to virus, regulation of wound healing, cellular response to virus, vasculogenesis, response to tumor necrosis factor, myeloid leukocyte migration, response to transforming growth factor beta, leukocyte chemotaxis, response to type II interferon, granulocyte chemotaxis, 	response to BMP, cellular response to BMP stimulus, regulation of BMP signaling pathway, regulation of integrin-mediated signaling pathway, 	 regulation of BMP signaling pathway, 	 regulation of cytokine-mediated signaling pathway, transforming growth factor beta receptor superfamily, response to chemokine, cellular response to chemokine, cellular response to fibroblast growth factor stimulus, cellular response to type II interferon, 	type II interferon-mediated signaling pathway, 	positive regulation of non-canonical NF-kappaB signal transduction, cellular response to interleukin-1, 	regulation of type I interferon-mediated signaling pathway, 	response to type I interferon, 	regulation of macrophage activation, cell adhesion mediated by integrin, tissue remodeling

```


```{r}
DEGenesTcells <- DEGenes %>% filter(cluster == "Tcells")

egoTcell <- enrichGO(gene = unique(DEGenesTcells$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)

egoTcell <- setReadable(egoTcell, OrgDb = org.Hs.eg.db)


dotplot(egoTcell, showCategory=20, title = "Tcell", font.size = 10)

View(egoTcell@result)

```


```{r}
DEGenesMph <- DEGenes %>% filter(cluster == "InflMph")

egoMph <- enrichGO(gene = unique(DEGenesMph$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)

egoMph <- setReadable(egoMph, OrgDb = org.Hs.eg.db)


dotplot(egoMph, showCategory=20, title = "Inflammatory Macrophages", font.size = 10)

View(egoMph@result)

```


```{r}
## Convert seurat_immun to single cell experiment (sce)
sce <- as.SingleCellExperiment(seuratM)
genes <- data.frame(geneID=rownames(sce)) %>% mutate(gene=gsub(".*\\.", "", geneID))
pal = colorRampPalette(c("#053061", "#2166ac", "#f7f7f7", "#f4a582","orange", "#d95f0e","#b2183c"))
scale_fill_gradientn(colors = pal(101), na.value = "grey90")

```



```{r}
## Subset healthy and convert seurat_Healthy to sce
seuratInflamed <- subset(seuratM, Inflammation_status == "Inflamed")
table(seuratInflamed$Inflammation_status)

sceInflamed <- as.SingleCellExperiment(seuratInflamed)
```

```{r}
## subset Acute Myocarditis (AM) from all disease conditions and convert seurat object to sce 
seuratNoninflamed <- subset(seuratAM, Inflammation_status == "Non-inflamed")
table(seuratM$Inflammation_status)
sceNoninflamed <- as.SingleCellExperiment(seuratNoninflamed)

```





